### ISSUE TITLE
Fix layout and copy in /signup-citizen

### ISSUE THREAD

**Issue by marvinsjsu** [Nonprofit-Exchange-Hub/web-frontend#4]
It looks like we need some spacing to be added between the header, content, and footer in `/signup-citizen`.  We also need to add copy, "Basic Information" section.

Current page layout:

![Image](https://user-images.githubusercontent.com/2562488/254433204-038259e8-13a7-4764-a6cd-1bc32e2efa04.png)

Figma layout:

![Image](https://user-images.githubusercontent.com/2562488/254433229-2b366f48-c24d-421f-837c-c3ece5cf1225.png)

Figma mocks - https://www.figma.com/file/K7DT5jYcLKRc9epmNrO0N7/UX---Dev-Handoff?type=design&node-id=1-5&mode=design&t=II3OZI8OgzhdP10A-0

**Comment by parvathi-kumar** [comment]
Finally got a chance to look through this - seems as though the issues at hand (spacing in between content and header/footer, basic information section) have been fixed. Should I close the issue @marvinsjsu
